name: Build Alpine Linux for Amlogic S9xxxx SoCs

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      mainline_linux_kernel_url:
        description: "Set mainline Linux kernel url."
        required: false
        default: "https://github.com/ophub/kernel/raw/main/pub/stable/6.0.10/boot-6.0.10-flippy-79%2B.tar.gz"
      kernel_modules_url:
        description: "Set kernel modules url."
        required: false
        default: "https://github.com/ophub/kernel/raw/main/pub/stable/6.0.10/modules-6.0.10-flippy-79%2B.tar.gz"      
      dtbs_url:
        description: "Set dtbs url."
        required: false
        default: "https://github.com/ophub/kernel/raw/main/pub/stable/6.0.10/dtb-amlogic-6.0.10-flippy-79%2B.tar.gz"
      alpine_linux_url:
        description: "Set Alpine Linux url."
        required: false
        default: "https://dl-cdn.alpinelinux.org/alpine/v3.17/releases/aarch64/alpine-uboot-3.17.0-aarch64.tar.gz"
      armbian_board:
        description: "Select Amlogic SoC."
        required: false
        default: "s905w"
        type: choice
        options:
          - all
          - a311d
          - s922x
          - s922x-n2
          - s922x-reva
          - s905x3
          - s905x3-b
          - s905x2
          - s905x2-km3
          - s912
          - s912-m8s
          - s905d
          - s905d-ki
          - s905x
          - s905w
          - s905
          - s905l3a
          - s905l2
